// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihibwnzkxaarmqchknbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloaWJ3bnpreGFhcm1xY2hrbmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDcxNzMsImV4cCI6MjA3NDQ4MzE3M30.wBXeirPOJLLoB8V1lRNN_3C8NjgInkC4jF67Gb8p2kE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});